# Generated by Django 3.1.7 on 2021-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_auto_20210306_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
